import {useEffect,useState} from 'react'
import {Link,useNavigate,useParams} from 'react-router-dom'
import {getProductById} from '../services/productApi'
import {useCart} from '../context/CartContext'
import {useAuth} from '../context/AuthContext'
import {getProductReviews,addProductReview} from '../services/reviewApi'
import {getWishlist,addToWishlist,removeFromWishlist} from '../services/wishlistApi'
export default function ProductDetails(){const{id}=useParams(),nav=useNavigate(),{addToCart}=useCart(),{isAuthenticated}=useAuth();const[p,setP]=useState(null),[reviews,setReviews]=useState([]),[wish,setWish]=useState(false),[comment,setComment]=useState(''),[rating,setRating]=useState(5),[error,setError]=useState('')
useEffect(()=>{(async()=>{try{setP(await getProductById(id));setReviews(await getProductReviews(id));if(isAuthenticated)setWish((await getWishlist()).products?.some(x=>x._id===id))}catch(e){setError(e.response?.data?.message||'Unable to load product')}})()},[id,isAuthenticated])
const review=async e=>{e.preventDefault();try{await addProductReview(id,Number(rating),comment);setComment('');setReviews(await getProductReviews(id))}catch(e){setError(e.response?.data?.message||'Unable to add review')}}
if(error&&!p)return <main className="p-8 text-center text-red-600">{error}</main>;if(!p)return <main className="p-8 text-center">Loading...</main>
const toggle=async()=>{if(!isAuthenticated)return nav('/login');const r=wish?await removeFromWishlist(id):await addToWishlist(id);setWish(r.products?.some(x=>x._id===id))}
return <main className="min-h-screen bg-slate-50 p-6 dark:bg-slate-950"><div className="mx-auto max-w-5xl"><Link to="/products">← Products</Link><div className="mt-5 grid gap-8 rounded-2xl border bg-white p-6 md:grid-cols-2 dark:bg-slate-900 dark:border-slate-800"><img src={p.imageUrl} alt={p.name} className="h-80 w-full object-contain bg-slate-100"/><div><div className="flex justify-between"><h1 className="text-3xl font-bold">{p.name}</h1><button onClick={toggle} className="text-2xl">{wish?'❤️':'♡'}</button></div><p className="mt-4 text-slate-600">{p.description}</p><p className="mt-5 text-2xl font-bold">₹{Number(p.price).toLocaleString('en-IN')}</p><p className="mt-2 text-sm">Stock: {p.stock}</p><button onClick={()=>addToCart({id:p._id,...p,image:p.imageUrl})} className="mt-6 w-full rounded-xl bg-slate-900 p-3 text-white">Add to Cart</button></div></div><section className="mt-8 rounded-2xl border bg-white p-6 dark:bg-slate-900"><h2 className="text-2xl font-bold">Reviews ({reviews.length})</h2>{reviews.map(r=><article key={r._id} className="mt-4 border-t pt-4"><b>{r.user?.name||'Customer'}</b> · ⭐ {r.rating}/5<p>{r.comment}</p></article>)}{isAuthenticated?<form onSubmit={review} className="mt-6 space-y-3"><select value={rating} onChange={e=>setRating(e.target.value)} className="border p-2"><option>5</option><option>4</option><option>3</option><option>2</option><option>1</option></select><textarea required maxLength={500} value={comment} onChange={e=>setComment(e.target.value)} className="w-full border p-3" placeholder="Write a review"/><button className="rounded bg-slate-900 px-4 py-2 text-white">Submit Review</button></form>:<Link to="/login" className="mt-5 inline-block text-blue-600">Login to review</Link>}</section></div></main>}