import {useEffect,useState} from 'react'
import ProductCard from '../components/ProductCard'
import {getProducts,getCategories} from '../services/productApi'
import laptop from '../assets/laptop.jpg'; import headphones from '../assets/headphones.jpg'; import smartwatch from '../assets/smartwatch.jpg'
const sortMap={default:'newest','price-low':'price_asc','price-high':'price_desc',name:'name_asc'}
function Products(){
 const [search,setSearch]=useState(''),[category,setCategory]=useState('all'),[sortBy,setSortBy]=useState('default'),[products,setProducts]=useState([]),[categories,setCategories]=useState([]),[page,setPage]=useState(1),[totalPages,setTotalPages]=useState(1),[total,setTotal]=useState(0),[loading,setLoading]=useState(true),[error,setError]=useState('')
 useEffect(()=>{getCategories().then(d=>setCategories(Array.isArray(d)?d:[])).catch(()=>{})},[])
 useEffect(()=>{(async()=>{try{setLoading(true);setError('');const r=await getProducts({search:search.trim()||undefined,category:category==='all'?undefined:category,sort:sortMap[sortBy],page,limit:9});setProducts((r.data||[]).map(p=>({...p,id:p._id,price:String(p.price),image:p.imageUrl||(p.category==='audio-headphones'?headphones:p.category==='smartwatches-wearables'?smartwatch:laptop)})));setTotal(r.total||0);setTotalPages(r.totalPages||1)}catch(e){setProducts([]);setError(e.response?.data?.message||'Unable to load products. Make sure backend is running.')}finally{setLoading(false)}})()},[search,category,sortBy,page])
 const clear=()=>{setSearch('');setCategory('all');setSortBy('default');setPage(1)}
 return <main className="min-h-screen bg-slate-50 px-4 py-8 dark:bg-slate-950"><div className="mx-auto max-w-7xl"><h1 className="text-3xl font-bold">Products</h1><div className="my-6 grid gap-4 md:grid-cols-3"><input value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}} placeholder="Search products..." className="rounded-xl border bg-white px-4 py-3 dark:border-slate-700 dark:bg-slate-900"/><select value={category} onChange={e=>{setCategory(e.target.value);setPage(1)}} className="rounded-xl border px-4 py-3 dark:border-slate-700 dark:bg-slate-900"><option value="all">All Products</option>{categories.map(c=><option key={c}>{c}</option>)}</select><select value={sortBy} onChange={e=>{setSortBy(e.target.value);setPage(1)}} className="rounded-xl border px-4 py-3 dark:border-slate-700 dark:bg-slate-900"><option value="default">Newest</option><option value="price-low">Price: Low to High</option><option value="price-high">Price: High to Low</option><option value="name">Name: A-Z</option></select></div>{loading&&<p className="text-center">Loading products...</p>}{error&&<p className="rounded-xl bg-red-50 p-5 text-center text-red-600">{error}</p>}{!loading&&!error&&<><div className="mb-5 flex justify-between text-sm text-slate-500"><span>Showing {products.length} of {total} · Page {page}/{totalPages}</span><button onClick={clear}>Clear Filters</button></div><div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">{products.map(p=><ProductCard key={p.id}{...p}/>)}</div>{!products.length&&<p className="mt-8 text-center">No products found.</p>}{totalPages>1&&<div className="mt-8 flex justify-center gap-4"><button disabled={page===1} onClick={()=>setPage(p=>p-1)}>Previous</button><span>{page} / {totalPages}</span><button disabled={page===totalPages} onClick={()=>setPage(p=>p+1)}>Next</button></div>}</>}</div></main>
}
export default Products